spring:
  application:
    name: account-service
    
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
      
feign:
  hystrix:
    enabled: true 
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
            
server:
  port: 8088            
            
                   