logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value} 
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka            