hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    account-service:
        path: /v1/accounts/**
        serviceId: account-service
        stripPrefix: false
        sensitiveHeaders:

    notification-services:
        path: /v1/notifications/**
        serviceId: notification-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value} 
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka