server:
  port: 8085
spring:
  application:
    name: notification-service
    
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value} 
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka

feign:
  hystrix:
    enabled: true 
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000       